#!/bin/bash

# Unlink Snap store from Discover
echo "Unlinking Snap store from Discover..."
sudo sed -i 's/Backend\s*=\s*snap/Backend=flatpak/g' /etc/xdg/kcms/discoverrc
echo "Snap store unlinked from Discover."

# Link Flathub to Discover
echo "Linking Flathub to Discover..."
sudo sed -i 's/Backend\s*=\s*flatpak/Backend=snap/g' /etc/xdg/kcms/discoverrc
echo "Flathub linked to Discover."

echo "Done."
