#!/bin/bash

#This script runs other scripts for installing and removing programs

if [ $(lsb_release -is) = 'Linuxmint' ];
    then programLM
fi

if [ $(lsb_release -is) = 'Ubuntu' ];
    then update
fi
