#!/bin/bash

#A script to install my favorite programs and uninstall programs that I do not want.

#Enable Firewall

sudo echo "*************ENABLING FIREWALL*************"

sudo ufw enable

#Update
sudo apt update

#Purge Programs

echo "*************PURGING PROGRAMS*************"

sudo apt purge libreoffice* -yy

sudo apt remove mono-runtime-common gnome-orca -yy

sudo apt purge hexchat -yy

sudo apt purge transmission-gtk -yy

sudo apt purge firefox -yy

sudo apt purge vlc -yy

sudo apt purge sticky -yy

sudo apt purge seahorse -yy

sudo apt purge thunderbird -yy

#Install Programs

echo "*************INSTALLING PROGRAMS*************"

# No need to install MS fonts. Comes with OnlyOffice.
# sudo apt install ttf-mscorefonts-installer -yy

sudo apt install htop -yy

sudo apt install simplescreenrecorder -yy

sudo apt install numlockx -yy

sudo apt install mc -yy

sudo apt install stacer -yy

sudo apt install mint-meta-codecs -yy

sudo apt install gparted -yy

sudo apt install brasero -yy

sudo apt install grub-customizer -yy

sudo apt install bulky -yy

sudo apt install parcellite -yy

#Install Brave Browser

sudo apt install apt-transport-https curl -yy

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-browser -yy

#Install Flatpak

flatpak install flathub org.onlyoffice.desktopeditors -yy

flatpak install flathub org.gnome.Cheese -yy

flatpak install flathub org.mozilla.firefox -yy

flatpak install flathub org.videolan.VLC -yy

flatpak install flathub fr.handbrake.ghb -yy

flatpak install flathub org.kde.kdenlive -yy

flatpak install flathub com.simplenote.Simplenote -yy

flatpak install flathub org.freefilesync.FreeFileSync -yy

flatpak install flathub org.jitsi.jitsi-meet -yy

flatpak install flathub org.signal.Signal -yy

flatpak install flathub org.audacityteam.Audacity -yy

flatpak install flathub org.videolan.VLC -yy

flatpak install flathub org.gnome.EasyTAG -yy

flatpak install flathub com.spotify.Client -yy

flatpak install flathub org.gtkhash.gtkhash -yy

flatpak install flathub org.mozilla.Thunderbird -yy

flatpak install flathub io.gitlab.librewolf-community -yy

flatpak install flathub org.js.nuclear.Nuclear -yy

flatpak install flathub org.gnome.Boxes -yy

flatpak install flathub org.flameshot.Flameshot -yy

flatpak install flathub com.obsproject.Studio -yy

flatpak install flathub org.gnome.Shotwell -yy

flatpak install flathub life.bolls.bolls -yy



#Remove, and Clean

echo "*************CLEANING*************"

sudo apt autoremove -yy

sudo apt autoclean -yy

#Fix popping sound on speakers due to sound card going to sleep in Linux Mint. Have Popsound file in bin before running. 

popsound_LM
