#!/bin/bash

#A script to install my favorite programs and uninstall programs that I do not want.

#Enable Firewall

sudo echo " _____ _   _    _    ____  _     ___ _   _  ____     _____ ___ ____  _______        ___    _     _
| ____| \ | |  / \  | __ )| |   |_ _| \ | |/ ___|   |  ___|_ _|  _ \| ____\ \      / / \  | |   | |
|  _| |  \| | / _ \ |  _ \| |    | ||  \| | |  _    | |_   | || |_) |  _|  \ \ /\ / / _ \ | |   | |
| |___| |\  |/ ___ \| |_) | |___ | || |\  | |_| |   |  _|  | ||  _ <| |___  \ V  V / ___ \| |___| |___
|_____|_| \_/_/   \_|____/|_____|___|_| \_|\________|_|   |___|_| \_|_____|  \_/\_/_/   \_|_____|_____|
                                               |_____|"

sudo ufw enable

#Update
sudo apt update

#Purge Programs

echo " ____  _   _ ____   ____ ___ _   _  ____     ____  ____   ___   ____ ____     _    __  __ ____
|  _ \| | | |  _ \ / ___|_ _| \ | |/ ___|   |  _ \|  _ \ / _ \ / ___|  _ \   / \  |  \/  / ___|
| |_) | | | | |_) | |  _ | ||  \| | |  _    | |_) | |_) | | | | |  _| |_) | / _ \ | |\/| \___ \
|  __/| |_| |  _ <| |_| || || |\  | |_| |   |  __/|  _ <| |_| | |_| |  _ < / ___ \| |  | |___) |
|_|    \___/|_| \_\\____|___|_| \_|\________|_|   |_| \_\\___/ \____|_| \_/_/   \_|_|  |_|____/
                                       |_____|"

sudo apt purge libreoffice* -yy

sudo apt remove mono-runtime-common gnome-orca -yy

sudo apt purge hexchat -yy

sudo apt purge transmission-gtk -yy

sudo apt purge firefox -yy

#Install Programs

echo " ___ _   _ ____ _____  _    _     _     ___ _   _  ____     ____  ____   ___   ____ ____     _    __  __ ____
|_ _| \ | / ___|_   _|/ \  | |   | |   |_ _| \ | |/ ___|   |  _ \|  _ \ / _ \ / ___|  _ \   / \  |  \/  / ___|
 | ||  \| \___ \ | | / _ \ | |   | |    | ||  \| | |  _    | |_) | |_) | | | | |  _| |_) | / _ \ | |\/| \___ \
 | || |\  |___) || |/ ___ \| |___| |___ | || |\  | |_| |   |  __/|  _ <| |_| | |_| |  _ < / ___ \| |  | |___) |
|___|_| \_|____/ |_/_/   \_|_____|_____|___|_| \_|\________|_|   |_| \_\\___/ \____|_| \_/_/   \_|_|  |_|____/
                                                      |_____|"

# No need to install MS fonts. Comes with OnlyOffice.
# sudo apt install ttf-mscorefonts-installer -yy

sudo apt install htop -yy

sudo apt install simplescreenrecorder -yy

sudo apt install numlockx -yy

sudo apt install mc -yy

sudo apt install easytag -yy

sudo apt install stacer -yy

sudo apt install vlc -yy

sudo apt install mint-meta-codecs -yy

sudo apt install gparted -yy

sudo apt install audacity -yy

sudo apt install gtkhash -yy



#Install Spotify

#curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
#echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
#sudo apt-get install spotify-client -yy

#Install Brave Browser

sudo apt install apt-transport-https curl -yy

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-browser -yy

#Install Flatpak

flatpak install flathub org.onlyoffice.desktopeditors -yy

flatpak install flathub org.gnome.Cheese -yy

flatpak install flathub org.mozilla.firefox -yy

flatpak install flathub org.videolan.VLC -yy

flatpak install flathub fr.handbrake.ghb -yy

flatpak install flathub org.kde.kdenlive -yy

flatpak install flathub com.simplenote.Simplenote -yy

flatpak install flathub org.freefilesync.FreeFileSync -yy

flatpak install flathub org.jitsi.jitsi-meet -yy

flatpak install flathub org.signal.Signal -yy

#Get Updated Key for Spotify

#curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -

#Remove, and Clean

echo "  ____ _     _____    _    _   _ ___ _   _  ____
 / ___| |   | ____|  / \  | \ | |_ _| \ | |/ ___|
| |   | |   |  _|   / _ \ |  \| || ||  \| | |  _
| |___| |___| |___ / ___ \| |\  || || |\  | |_| |
 \____|_____|_____/_/   \_|_| \_|___|_| \_|\____|
"

sudo apt autoremove -yy

sudo apt autoclean -yy

#Fix popping sound on speakers due to sound card going to sleep in Linux Mint. Have Popsound file in bin before running. 

popsound_LM
