#!/bin/bash

#This script runs other scripts for installing and removing programs

if [ $(lsb_release -is) = 'Linuxmint' ];
    then guess
fi

if [ $(lsb_release -is) = 'Ubuntu' ];
    then update
fi
