#!/bin/bash

#Make the bin directory

mkdir /home/tim/bin

#Download Bash Scripts

wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/up -P /home/tim/bin

wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/programs -P /home/tim/bin

wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/popsound_LM -P /home/tim/bin

#Make scripts executable

sudo chmod +x /home/tim/bin/up

sudo chmod +x /home/tim/bin/programs

sudo chmod +x /home/tim/bin/popsound_LM

#Search for "bin" directory to add it to bin path

test -d "$HOME/bin" && PATH="$HOME/bin:$PATH"

#Run the intial update and program setup

up

programs

echo "Your intial setup should be done!"
