#!/bin/bash

echo "****************"
echo "*  UPDATE 1.1  *"
echo "****************"

sudo echo "***************************"
echo "*  UPDATING PACKAGE INFO  *"
echo "***************************"

sudo apt update -yy

echo "***********************************"
echo "*  PERFORMING FULL SYSTEM UPDATE  *"
echo "***********************************"

sudo apt full-upgrade -yy

echo "************************************"
echo "*  UPDATING FLATPAKS               *"
echo "************************************"

flatpak update

echo "************************************"
echo "*  REMOVING UNEEDED PACKAGE FILES  *"
echo "************************************"

sudo apt autoremove -yy
sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy

echo "***************************"
echo "*  CLEANING UP OLD FILES  *"
echo "***************************"

sudo apt autoclean -yy

echo "****************************"
echo "*  SYSTEM UPDATE COMPLETE!  *"
echo "****************************"
